In [64]:
import numpy as np

In [65]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.utils import shuffle
import pandas as pd

#Loading datasets

In [66]:
tictac_data_single = np.loadtxt('tictac_single.txt')
X = tictac_data_single[:,:9]
y = tictac_data_single[:,9]
y

array([6., 1., 2., ..., 2., 0., 4.])

In [67]:
X_shuffled_single, y_shuffled_single = shuffle(X, y, random_state=42)
X_train_single, X_test_single, y_train_single, y_test_single = train_test_split(X_shuffled_single, y_shuffled_single, test_size=0.9)

In [68]:
tictac_data_final = np.loadtxt('tictac_final.txt')
X = tictac_data_final[:,:9]
y = tictac_data_final[:,9]

In [69]:
X_shuffled_final, y_shuffled_final = shuffle(X, y, random_state=42)
X_train_final, X_test_final, y_train_final, y_test_final = train_test_split(X_shuffled_final, y_shuffled_final, test_size=0.9)

In [70]:
tictac_data_multi = np.loadtxt('tictac_multi.txt')
X = tictac_data_multi[:,:9]
y = tictac_data_multi[:,9:]
# change how picking last nine, change loading
#np.sum(y == 1, axis=1)
print(y.shape[0])
y

6551


array([[0., 0., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 1., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       ...,
       [0., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [71]:
X_shuffled_multi, y_shuffled_multi = shuffle(X, y, random_state=42)
X_train_multi, X_test_multi, y_train_multi, y_test_multi = train_test_split(X_shuffled_multi, y_shuffled_multi, test_size=0.9)
#np.set_printoptions(threshold=np.inf)
#print(y_test_multi)
from IPython.display import display
display(y_test_multi)
print(y_test_multi.shape)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

(5896, 9)


In [72]:
def svm_model(X_train, y_train, X_test, y_test):
  svm_model = SVC(kernel='linear')
  svm_model.fit(X_train, y_train)
  y_pred = svm_model.predict(X_test)
  svm_accuracy = cross_val_score(svm_model, X_train, y_train, cv=10, scoring="accuracy").mean()
  conf_matrix = confusion_matrix(y_test, y_pred, normalize = "true")
  print(f"SVM(Linear) Accuracy: {svm_accuracy}")
  print("Confusion Matrix:")
  print(conf_matrix)
  return

#SVM using single dataset

In [73]:
svm_model(X_train_single, y_train_single, X_test_single, y_test_single)

SVM(Linear) Accuracy: 0.4580186480186481
Confusion Matrix:
[[1.         0.         0.         0.         0.         0.         0.         0.         0.        ]
 [0.11313394 0.37971391 0.33029909 0.00650195 0.10013004 0.         0.03511053 0.         0.03511053]
 [0.1766055  0.1146789  0.7087156  0.         0.         0.         0.         0.         0.        ]
 [0.15317287 0.05251641 0.4463895  0.16411379 0.10284464 0.00656455 0.03938731 0.         0.03501094]
 [0.28829787 0.05851064 0.42659574 0.05744681 0.16914894 0.         0.         0.         0.        ]
 [0.26397516 0.08074534 0.44099379 0.0310559  0.01863354 0.03726708 0.06832298 0.         0.05900621]
 [0.25050916 0.05498982 0.42769857 0.13441955 0.03869654 0.00407332 0.08350305 0.         0.00610998]
 [0.29955947 0.04845815 0.35242291 0.03524229 0.0660793  0.00881057 0.08810573 0.         0.10132159]
 [0.26823529 0.05176471 0.47058824 0.05647059 0.03294118 0.03529412 0.05647059 0.00470588 0.02352941]]


d

#SVM using final dataset

In [74]:
svm_model(X_train_final, y_train_final, X_test_final, y_test_final)

SVM(Linear) Accuracy: 0.99
Confusion Matrix:
[[0.94966443 0.05033557]
 [0.         1.        ]]


In [75]:
from sklearn.neighbors import KNeighborsClassifier

In [76]:
def knn_model(X_train, y_train, X_test, y_test):
  knn_model = KNeighborsClassifier(n_neighbors=5)
  knn_model.fit(X_train, y_train)
  y_pred = knn_model.predict(X_test)
  knn_accuracy = cross_val_score(knn_model, X_train, y_train, cv=10, scoring="accuracy").mean()
  #knn_accuracy = accuracy_score(y_test, y_pred)
  conf_matrix = confusion_matrix(y_test, y_pred, normalize = "true")
  print(f"KNN Accuracy: {knn_accuracy}")
  print("Confusion Matrix:")
  print(conf_matrix)
  return

#KneighborsClassifier - single dataset

In [77]:
knn_model(X_train_single, y_train_single, X_test_single, y_test_single)

KNN Accuracy: 0.5617016317016317
Confusion Matrix:
[[0.82842785 0.02727925 0.03589375 0.01651113 0.04881551 0.017229   0.01076813 0.00430725 0.01076813]
 [0.1443433  0.526658   0.08582575 0.04161248 0.1053316  0.02860858 0.02990897 0.01950585 0.01820546]
 [0.17087156 0.07912844 0.59174312 0.02866972 0.08830275 0.00802752 0.02178899 0.00917431 0.00229358]
 [0.21006565 0.07877462 0.04157549 0.45295405 0.10284464 0.01531729 0.04157549 0.03501094 0.02188184]
 [0.19468085 0.05319149 0.09468085 0.02340426 0.5893617  0.00212766 0.02978723 0.         0.01276596]
 [0.21428571 0.05590062 0.13354037 0.05900621 0.17080745 0.27018634 0.04347826 0.04037267 0.01242236]
 [0.27087576 0.04887984 0.09368635 0.08961303 0.08553971 0.01629328 0.37270876 0.01425662 0.00814664]
 [0.2246696  0.14096916 0.07929515 0.0969163  0.08370044 0.04405286 0.03524229 0.25110132 0.04405286]
 [0.25882353 0.12705882 0.10588235 0.03764706 0.13176471 0.02588235 0.04470588 0.02352941 0.24470588]]


#KneighborsClassifier - final dataset

In [78]:
knn_model(X_train_final, y_train_final, X_test_final, y_test_final)

KNN Accuracy: 0.7988888888888889
Confusion Matrix:
[[0.68791946 0.31208054]
 [0.04778761 0.95221239]]


In [79]:
from sklearn.neural_network import MLPClassifier

In [80]:
def mlp_model(X_train, y_train, X_test, y_test):
  mlp_model = MLPClassifier(hidden_layer_sizes=(128, 32), max_iter=100)
  mlp_model.fit(X_train, y_train)
  y_pred = mlp_model.predict(X_test)
  mlp_accuracy = cross_val_score(mlp_model, X_train, y_train, cv=10, scoring="accuracy").mean()
  conf_matrix = confusion_matrix(y_test, y_pred, normalize = "true")
  print(f"Multilayer Perceptron Accuracy: {mlp_accuracy}")
  print("Confusion Matrix:")
  print(conf_matrix)
  return

#Multilayer Perceptron - single dataset

In [81]:
mlp_model(X_train_single, y_train_single, X_test_single, y_test_single)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptro

Multilayer Perceptron Accuracy: 0.671864801864802
Confusion Matrix:
[[0.90882986 0.005743   0.02081838 0.0086145  0.02368988 0.00646088 0.011486   0.00358938 0.01076813]
 [0.06111834 0.59427828 0.15214564 0.06762029 0.05721717 0.02730819 0.01950585 0.00780234 0.0130039 ]
 [0.07912844 0.04472477 0.75688073 0.03784404 0.04931193 0.01146789 0.00458716 0.01490826 0.00114679]
 [0.0678337  0.0547046  0.01531729 0.57986871 0.11597374 0.04595186 0.05908096 0.02625821 0.03501094]
 [0.09361702 0.04255319 0.0287234  0.01276596 0.78297872 0.00744681 0.02978723 0.         0.00212766]
 [0.09627329 0.02484472 0.0931677  0.19565217 0.04968944 0.36024845 0.08074534 0.04658385 0.05279503]
 [0.13441955 0.05295316 0.06517312 0.09368635 0.04887984 0.0407332  0.53971487 0.0203666  0.00407332]
 [0.13215859 0.18061674 0.06167401 0.07929515 0.05726872 0.030837   0.04405286 0.36563877 0.04845815]
 [0.21176471 0.12941176 0.10823529 0.08470588 0.04705882 0.03058824 0.03764706 0.05647059 0.29411765]]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


#Multilayer Perceptron - Final


In [82]:
mlp_model(X_train_final, y_train_final, X_test_final, y_test_final)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptro

Multilayer Perceptron Accuracy: 0.7711111111111111
Confusion Matrix:
[[0.7852349  0.2147651 ]
 [0.08318584 0.91681416]]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


#KNN Regression - multi

In [83]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import r2_score

In [84]:
knn_regressor = KNeighborsRegressor(n_neighbors=5)

In [85]:
#multioutput_knn = MultiOutputRegressor(knn_regressor)
#y_train_multi = y_train_multi.reshape(-1, 1)
#y_train_multi = np.tile(y_train_multi, (1, 9))
#multioutput_knn.fit(X_train_multi, y_train_multi)
knn_regressor.fit(X_train_multi, y_train_multi)

KNeighborsRegressor()

In [86]:
y_pred = knn_regressor.predict(X_test_multi)
#knn_pred = np.round(multioutput_knn.predict(X_test_multi))

In [87]:
#knn_r2_score = mean_squared_error(y_test, y_pred)
knn_r2_score = cross_val_score(knn_regressor, X_shuffled_multi, y_shuffled_multi, cv=10, scoring="r2").mean()
#knn_r2_score = r2_score(y_test_multi, knn_pred)
#conf_matrix = confusion_matrix(y_test, y_pred)

In [88]:
print(f"KNN Regressor Accuracy: {knn_r2_score }")

KNN Regressor Accuracy: 0.5832841824144476


In [89]:
#print("Confusion Matrix:")
#print(conf_matrix)

#Linear Regression - multi

In [90]:
from sklearn.linear_model import LinearRegression

In [91]:
#linear_regressor = LinearRegression()
linear_models = []

In [92]:
#linear_regressor.fit(X_train_multi, y_train_multi)
for i in range(9):
    linear_regressor = LinearRegression()
    linear_regressor.fit(X_train_multi, y_train_multi[:, i])
    linear_models.append(linear_regressor)


In [93]:
#y_pred = linear_regressor.predict(X_test_multi)
np.set_printoptions(linewidth=np.inf)
linear_outputs = np.array([np.round(model.predict(X_test_multi)) for model in linear_models]).T
linear_pred = np.argmax(linear_outputs, axis=1)
print(linear_outputs)
print(linear_pred)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[0 0 0 ... 0 0 0]


In [94]:
#linear_r2_score = cross_val_score(linear_regressor, X_train_multi, X_train_multi, cv=10, scoring="r2").mean()
linear_accuracy = accuracy_score(np.argmax(y_test_multi, axis=1), linear_pred)

In [95]:
print(f"Linear Regression Accuracy: {linear_accuracy }")

Linear Regression Accuracy: 0.24135006784260515


# Multilayer Regression - Multi

In [96]:
from sklearn.neural_network import MLPRegressor

In [97]:
mlp_regressor = MLPRegressor(hidden_layer_sizes=(128, 32), activation='relu', max_iter=100, random_state=42) #128,
#mlp_regressor = MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42)

In [98]:
mlp_regressor.fit(X_train_multi, y_train_multi)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(hidden_layer_sizes=(128, 32), max_iter=100, random_state=42)

In [99]:
y_pred = mlp_regressor.predict(X_test_multi) # do osmething like this for linear no need for mlp

In [100]:
# consider using root mean square error, no confusion matrix
mlp_r2_score = cross_val_score(mlp_regressor, X_shuffled_multi, y_shuffled_multi, cv=10, scoring="r2").mean()

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptro

In [101]:
print(f"Multilayer Regression Accuracy: {mlp_r2_score }")

Multilayer Regression Accuracy: 0.6276074011988595


#Linear Regression - Normal Equation (Extra Credit)

In [102]:
#From textbook
from sklearn.preprocessing import add_dummy_feature


X_b = add_dummy_feature(X_train_multi)  # add x0 = 1 to each instance
theta_best = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y_train_multi

In [103]:
theta_best

array([[ 2.24236538e-01,  1.89600582e-01,  2.36057889e-01,  1.53654358e-01,  2.75904966e-01,  1.72218485e-01,  2.57146620e-01,  1.42255940e-01,  2.10123001e-01],
       [-1.21645405e-02, -1.63288633e-02,  2.12357679e-02,  2.22798490e-02,  2.82586857e-02,  9.12773768e-03, -1.33384954e-02,  4.52462474e-02,  2.81150273e-02],
       [ 1.52823534e-02, -4.75844386e-02, -1.15477188e-02,  4.52462333e-02,  4.66726974e-03,  2.15900722e-02,  2.92274559e-02,  2.78423587e-02,  7.51895097e-03],
       [-6.94292931e-03, -2.39235450e-02, -1.95371151e-02,  1.07469019e-02, -1.04765643e-02,  1.95261651e-02,  4.85315340e-02, -1.19477584e-02,  2.82782374e-02],
       [ 2.28468293e-02,  1.63395717e-02, -6.07825437e-03,  1.34158123e-04,  1.06016465e-02, -7.32150027e-03, -5.47129154e-03,  4.86906613e-02,  8.95347676e-03],
       [-1.72638136e-03, -7.96728427e-03,  1.46677460e-02,  1.35914491e-02, -7.27893764e-03, -5.79658991e-03,  1.27224426e-02,  7.55012806e-03,  4.78818315e-03],
       [-2.94627563e-02,  3.